### ISSUE TITLE
Parsing fails for `Cargo.toml` with profile

### ISSUE THREAD

**Issue by ggwpez** [paritytech/cargo-unleash#104]
Feels more like a DQ to me; Parsing a `Cargo.toml` with a profile fails (eg. [Substrates'](https://github.com/paritytech/substrate/blob/1802a115e8480fd7a4654d45c85b58c2189c508a/Cargo.toml#L301)):  
```toml
[workspace]

members = [ ]

[profile.production]
inherits = "release"
```
results in:
```pre
$ cargo unleash --manifest-path Cargo.toml em-dragons
Error: "Reading workspace \"Cargo.toml\" failed: failed to parse manifest at `Cargo.toml`
```
It works fine without the profile definition.
